# add audible to the list of plugins
# copyartifacts is optional but recommended if you're manually specifying metadata via metadata.yml, see the "Importing non-audible content" section
# also add the "web" plugin if using the docker image
plugins: audible copyartifacts edit fromfilename scrub web permissions

web:
    host: 0.0.0.0
    port: 8337
    cors: '*'
    reverse_proxy: 

directory: /path/to/audiobooks/library

move: yes

permissions:
    file: 777
    dir: 777

# Place books in their own folders to be compatible with Booksonic and Audiobookshelf servers
paths:
  # For books that belong to a series
  # "albumtype:audiobook series_name::.+ series_position::.+": $albumartist/%ifdef{series_name}/%ifdef{series_position} - $album%aunique{}/$track - $title
  # "albumtype:audiobook series_name::.+ series_position::.+": $albumartist - %ifdef{series_name} - %ifdef{series_position} - $album%aunique{}/$track - $title
  "albumtype:audiobook series_name::.+ series_position::.+": $albumartist/%ifdef{series_name}/%ifdef{series_position} $album%aunique{}/$title - $albumartist
  # "albumtype:audiobook series_name::.+": $albumartist/%ifdef{series_name}/$album%aunique{}/$track - $title
  # "albumtype:audiobook series_name::.+": $albumartist - %ifdef{series_name} - $album%aunique{}/$track - $title
  "albumtype:audiobook series_name::.+": $albumartist/%ifdef{series_name}/%ifdef{series_position} $album%aunique{}/$title - $albumartist
  # Stand-alone books
  # "albumtype:audiobook": $albumartist/$album%aunique{}/$track - $title
  "albumtype:audiobook": $albumartist/$album%aunique{}/$title - $albumartist
  # default: $albumartist/$album%aunique{}/$track - $title
  default: $albumartist - $album%aunique{}/$title
  singleton: $albumartist/$title
  comp: Compilations/$album%aunique{}/$track - $title
  albumtype_soundtrack: Soundtracks/$album/$track $title

# disables musicbrainz lookup, as it doesn't help for audiobooks
musicbrainz:
  enabled: no

audible:
  # if the number of files in the book is the same as the number of chapters from Audible,
  # attempt to match each file to an audible chapter
#   goodreads_apikey: [APIKEYHERE] #optional
  match_chapters: true
  source_weight: 0.0 # disable the source_weight penalty
  fetch_art: true # whether to retrieve cover art
  include_narrator_in_artists: false # include author and narrator in artist tag. Or just author
  keep_series_reference_in_title: false # set to false to remove ", Book X" from end of titles
  keep_series_reference_in_subtitle: true # set to false to remove subtitle if it contains the series name and the word book ex. "Book 1 in Great Series", "Great Series, Book 1"
  write_description_file: true # output desc.txt
  write_reader_file: true # output reader.txt
  region: us # the region from which to obtain metadata can be omitted, by default it is "us"
             # pick one of the available values: au, ca, de, es, fr, in, it, jp, us, uk
             # the region value can be set for each book individually during import/re-import
             # also it is automatically derived from 'WOAF' (WWWAUDIOFILE) tag
             # which may contain a URL such as 'https://www.audible.com/pd/ASINSTRING' or 'audible.com'

copyartifacts:
  extensions: .yml .yaml .nfo .txt .json .jpg .png .ico .cue # so that metadata.yml is copied, see below

scrub:
  auto: yes # optional, enabling this is personal preference